@url = http://localhost:3511

### ROOT
GET {{url}}

### GET WELCOME MESSAGE
GET {{url}}/welcomemessage

### SAVE WELCOME MESSAGE
POST {{url}}/welcomemessage
content-type: application/json

{
	"welcomeMessage": "Welcome to this site. (CHANGED)"
}

### BAD LOGIN 
POST {{url}}/login
content-type: application/json

{
	"password": "badpassword"
}

### SUCCESSFUL LOGIN
POST {{url}}/login
content-type: application/json

{
	"password": "123"
}

### GET CURRENT USER
POST {{url}}/currentuser
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImZpcnN0TmFtZSI6IkFkbWluIiwibGFzdE5hbWUiOiJVc2VyIiwiYWNjZXNzR3JvdXBzIjpbImxvZ2dlZEluVXNlcnMiLCJhZG1pbnMiXX0sImlhdCI6MTY3NTA3NTE2MywiZXhwIjoxNjc1MDc1MTgzfQ.2pZtEP0hjjcTHzcX0rKXAxxhatQcVFIqyhlxE93E8cI